name: Scheduler
on:
  schedule:
    - cron:  '0/5 13 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: boot ola task
      run: curl https://olove-archive-and-ok-ng.herokuapp.com/boot-archiver
